export const GET_POSTS = "GET_POSTS";
export const GET_POST = "GET_POST";
export const POST_ERROR = "POST_ERROR";
export const UPDATE_POST = "UPDATE_POST";
export const DELETE_POST = "DELETE_POST";
export const ADD_POST = "ADD_POST";

export const GET_ABOUT_PARAGRAPHS = "GET_ABOUT_PARAGRAPHS";
export const GET_ABOUT_PROJECTS = "GET_ABOUT_PROJECTS";
export const UPDATE_ABOUT_PARAGRAPH = "UPDATE_ABOUT_PARAGRAPH";
export const UPDATE_ABOUT_PROJECT = "UPDATE_ABOUT_PROJECT";
export const ADD_ABOUT_PARAGRAPH = "ADD_ABOUT_PARAGRAPH";
export const ADD_ABOUT_PROJECT = "ADD_ABOUT_PROJECT";
export const DELETE_ABOUT_PARAGRAPH = "DELETE_ABOUT_PARAGRAPH";
export const DELETE_ABOUT_PROJECT = "DELETE_ABOUT_PROJECT";
export const ABOUT_ERROR = "ABOUT_ERROR";
